"""add occurrence id to occurence model

Revision ID: bd7d286289b0
Revises: d115e9b76320
Create Date: 2026-09-06 14:01:08.581575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7d286289b0'
down_revision: Union[str, Sequence[str], None] = 'd115e9b76320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occurrences', sa.Column('occurrence_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_occurrences_occurrence_id'), 'occurrences', ['occurrence_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occurrences_occurrence_id'), table_name='occurrences')
    op.drop_column('occurrences', 'occurrence_id')
    # ### end Alembic commands ###
