"""fix occurrence source identifier

Revision ID: 995d5d974e8f
Revises: bd7d286289b0
Create Date: 2026-09-06 14:58:01.700278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995d5d974e8f'
down_revision: Union[str, Sequence[str], None] = 'bd7d286289b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('occurrences', 'occurrence_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               nullable=True,
               postgresql_using='occurrence_id::text')
    op.drop_index(op.f('ix_occurrences_occurrence_id'), table_name='occurrences')
    op.create_index(op.f('ix_occurrences_occurrence_id'), 'occurrences', ['occurrence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occurrences_occurrence_id'), table_name='occurrences')
    op.create_index(op.f('ix_occurrences_occurrence_id'), 'occurrences', ['occurrence_id'], unique=True)
    op.alter_column('occurrences', 'occurrence_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=False,
               postgresql_using='occurrence_id::bigint')
    # ### end Alembic commands ###
