"""create coupis tables

Revision ID: d115e9b76320
Revises: 
Create Date: 2026-09-06 12:13:31.643552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd115e9b76320'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gbif_dataset_key', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_gbif_dataset_key'), 'datasets', ['gbif_dataset_key'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gbif_taxon_key', sa.BigInteger(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('vernacular_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_gbif_taxon_key'), 'species', ['gbif_taxon_key'], unique=True)
    op.create_geospatial_table('occurrences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gbif_id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coordinate_uncertainty_m', sa.Float(), nullable=True),
    sa.Column('basis_of_record', sa.String(), nullable=True),
    sa.Column('occurrence_status', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('issues', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_occurrences_geom', 'occurrences', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_occurrences_gbif_id'), 'occurrences', ['gbif_id'], unique=True)
    op.create_index(op.f('ix_occurrences_species_id'), 'occurrences', ['species_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occurrences_species_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_gbif_id'), table_name='occurrences')
    op.drop_geospatial_index('idx_occurrences_geom', table_name='occurrences', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('occurrences')
    op.drop_index(op.f('ix_species_gbif_taxon_key'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_datasets_gbif_dataset_key'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
